name: amd64_windows_gcc

on: workflow_dispatch

jobs:

  amd64_windows_gcc:
    runs-on: windows-2019
    env:
      CC: gcc
    steps:
    - uses: actions/checkout@v2
    # - run: echo "::add-path::C:\\msys64\\usr\\bin"
    - run: echo "C:\msys64\usr\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    - run: pacman --version
    - run: pacman -Sy
    - run: pacman --noconfirm -S pacman-mirrors
    - name: 'Install requirements'
      run: pacman --noconfirm -S mingw64/mingw-w64-x86_64-toolchain mingw64/mingw-w64-x86_64-cmake mingw64/mingw-w64-x86_64-qtwebkit mingw64/mingw-w64-x86_64-python2
    # - run: echo "::add-path::C:\\msys64\\mingw64\\bin"
    - run: echo "C:\msys64\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    - run: g++ --version && cmake --version && qmake --version
      name: 'Display tools version'
    - run: bash ./configure
      name: './configure'
      env:
        CMAKE_CMD: 'cmake -G "MinGW Makefiles"'
    - run: mingw32-make
      name: 'make'
    - run: file ./bin/phantomjs
    - run: ldd ./bin/phantomjs
    - run: ./bin/phantomjs --version
    - uses: actions/upload-artifact@v2
      with:
        name: amd64_windows_gcc
        path: ./bin/phantomjs*
